version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50
  - package-ecosystem: "docker"
    directory: "/packages/e2e/"
    schedule:
      interval: "daily"
